# Generated by Django 2.0.1 on 2018-05-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=225, primary_key=True, serialize=False, verbose_name='Email')),
                ('key', models.CharField(blank=True, max_length=20, null=True)),
                ('key_date', models.DateTimeField()),
                ('_slug', models.SlugField()),
                ('active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('_referee', models.BooleanField(default=False)),
                ('_athlete', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
