# Generated by Django 2.0.1 on 2018-05-30 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_slug',
            new_name='slug',
        ),
    ]
