"""
Django settings for main Project.

Generated by 'django-admin startproject' using Django 2.0.5.

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

try:
    from .base import *
except ImportError:
    from .production import *
finally:
    try:
        from .local import *
    except ImportError:
        pass
